export const SET_CATEGORY_ACTION = "SET_CATEGORY_ACTION";
export const GET_CATEGORY_ACTION = "GET_CATEGORY_ACTION";
export const GET_DB_CATEGORY_ACTION = "GET_DB_CATEGORY_ACTION";
export const ADD_CATEGORY_ACTION = "ADD_CATEGORY_ACTION";
export const DELETE_CATEGORY_ACTION = "DELETE_CATEGORY_ACTION";
export const SET_LOADING_ACTION = "SET_LOADING_ACTION";
export const GET_LOADING_ACTION = "GET_LOADING_ACTION";
